# Check textdata

## namelist

Are all codes unique per language?

```{r}
read_vc(namelist_path) %>% 
    count(code, lang) %>% 
    filter(n > 1) %>% 
    nrow == 0
```

## types

Are all codes unique?

```{r}
read_vc(types_path) %>% 
    count(type) %>% 
    filter(n > 1) %>% 
    nrow == 0
```

Are all main types correct?

```{r}
read_vc(types_path) %>% 
    mutate(main_type_2 = ifelse(str_detect(type, "_"),
                                str_sub(type, 
                                        end = str_locate(type, "_") - 1),
                                type)
    ) %>% 
    filter(main_type != main_type_2) %>% 
    nrow == 0
```

## env_pressures

Are all codes unique?

```{r}
read_vc(ep_path) %>% 
    count(ep_code) %>% 
    filter(n > 1) %>% 
    nrow == 0
```

Do ep_classes coincide between ep_code and ep_class?

```{r}
read_vc(ep_path) %>% 
    mutate(ep_class_c = str_c("ep_class_",
                        str_match(ep_code, "ep_(..).*")[,2]
                        ),
           ep_class = as.character(ep_class)
    ) %>% 
    (function(df) {
        all.equal(df$ep_class_c, df$ep_class)
    })
```

Do ep_classes coincide between ep_code and explanation?

```{r}
read_vc(ep_path) %>% 
    mutate(ep_class_c1 = str_match(ep_code, "ep_(..).*")[,2],
           ep_class_c2 = str_match(explanation, "ep_(..).*")[,2],
    ) %>% 
    (function(df) {
        all.equal(df$ep_class_c1, df$ep_class_c2)
    })
```

